name: 天天充电自动签到

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-dailycharge:
    name: Run DailyCharge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DailyCharge Sign-in
        env:
          DAILYCHARGE_UID: ${{ secrets.DAILYCHARGE_UID }}
          DAILYCHARGE_USERID_LOCKED: ${{ secrets.DAILYCHARGE_USERID_LOCKED }}
          DAILYCHARGE_USERID_OPEN: ${{ secrets.DAILYCHARGE_USERID_OPEN }}
          COMBINED_SUMMARY_MODE: 'yes'
        run: python dailycharge/dailycharge_signin.py
