name: 塔斯汀自动脚本

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  run-tastien:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tastien Scripts
        env:
          tsthbck: ${{ secrets.TASTIEN_USER_TOKENS }}
          SERVER_CHAN_SEND_KEY: ${{ secrets.SERVER_CHAN_SEND_KEY }}
        run: |
          echo "=== 开始执行塔斯汀每日签到 ==="
          python tastien/tastien_checkin.py
